import * as  __HMR__ from '/_hmr_client.js?namespace=hmr-client'; import.meta.hot = __HMR__.createHotContext(import.meta.url); import "/App.svelte.css?namespace=file";
/* fixtures/with-svelte/App.svelte generated by Svelte v3.32.1 */
import {
	SvelteComponentDev,
	add_location,
	append_dev,
	attr_dev,
	detach_dev,
	dispatch_dev,
	element,
	init,
	insert_dev,
	listen_dev,
	noop,
	run_all,
	safe_not_equal,
	set_data_dev,
	space,
	text,
	validate_slots
} from "/.bundless/web_modules/svelte/internal/index.js?namespace=file";

const file = "fixtures/with-svelte/App.svelte";

function create_fragment(ctx) {
	let div;
	let t0;
	let t1;
	let t2;
	let button0;
	let t4;
	let button1;
	let mounted;
	let dispose;

	const block = {
		c: function create() {
			div = element("div");
			t0 = text("counts: ");
			t1 = text(/*count*/ ctx[0]);
			t2 = space();
			button0 = element("button");
			button0.textContent = "increment";
			t4 = space();
			button1 = element("button");
			button1.textContent = "decrement";
			attr_dev(div, "class", "svelte-1x83jhu");
			add_location(div, file, 5, 0, 114);
			add_location(button0, file, 6, 0, 141);
			add_location(button1, file, 7, 0, 189);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, div, anchor);
			append_dev(div, t0);
			append_dev(div, t1);
			insert_dev(target, t2, anchor);
			insert_dev(target, button0, anchor);
			insert_dev(target, t4, anchor);
			insert_dev(target, button1, anchor);

			if (!mounted) {
				dispose = [
					listen_dev(button0, "click", /*increment*/ ctx[1], false, false, false),
					listen_dev(button1, "click", /*decrement*/ ctx[2], false, false, false)
				];

				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*count*/ 1) set_data_dev(t1, /*count*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(div);
			if (detaching) detach_dev(t2);
			if (detaching) detach_dev(button0);
			if (detaching) detach_dev(t4);
			if (detaching) detach_dev(button1);
			mounted = false;
			run_all(dispose);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots("App", slots, []);
	let count = 0;
	let increment = () => $$invalidate(0, count++, count);
	let decrement = () => $$invalidate(0, count--, count);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<App> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({ count, increment, decrement });

	$$self.$inject_state = $$props => {
		if ("count" in $$props) $$invalidate(0, count = $$props.count);
		if ("increment" in $$props) $$invalidate(1, increment = $$props.increment);
		if ("decrement" in $$props) $$invalidate(2, decrement = $$props.decrement);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [count, increment, decrement];
}

class App extends SvelteComponentDev {
	constructor(options) {
		super(options);
		init(this, options, instance, create_fragment, safe_not_equal, {});

		dispatch_dev("SvelteRegisterComponent", {
			component: this,
			tagName: "App",
			options,
			id: create_fragment.name
		});
	}
}
import * as ___SVELTE_HMR_HOT_API from '/.bundless/web_modules/svelte-hmr/runtime/hot-api-esm.js?namespace=file';import svelteHmr_runtime_proxyAdapterDom_js_cjsImport3 from "/.bundless/web_modules/svelte-hmr/runtime/proxy-adapter-dom.js?namespace=file"; const ___SVELTE_HMR_HOT_API_PROXY_ADAPTER = svelteHmr_runtime_proxyAdapterDom_js_cjsImport3 && svelteHmr_runtime_proxyAdapterDom_js_cjsImport3.__esModule ? svelteHmr_runtime_proxyAdapterDom_js_cjsImport3.default : svelteHmr_runtime_proxyAdapterDom_js_cjsImport3;;if (import.meta && import.meta.hot) { App = ___SVELTE_HMR_HOT_API.applyHmr({ m: import.meta, id: "/Users/morse/Documents/GitHub/espack/fixtures/with-svelte/App.svelte", hotOptions: {"preserveLocalState":true,"noPreserveStateKey":["@hmr:reset","@!hmr"],"preserveAllLocalStateKey":"@hmr:keep-all","preserveLocalStateKey":"@hmr:keep","noReload":false,"optimistic":true,"acceptNamedExports":true,"acceptAccessors":true,"injectCss":true,"cssEjectDelay":100,"native":false,"compatVite":false,"importAdapterName":"___SVELTE_HMR_HOT_API_PROXY_ADAPTER","absoluteImports":false,"noOverlay":true}, Component: App, ProxyAdapter: ___SVELTE_HMR_HOT_API_PROXY_ADAPTER, acceptable: true, cssId: "svelte-1x83jhu-style", nonCssHash: "564uli", }); }
export default App;

if (typeof add_css !== 'undefined' && !document.getElementById("svelte-1x83jhu-style")) add_css();
